apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ice-basins-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Match this to your PV's storage
  storageClassName: ""
