apiVersion: v1
kind: PersistentVolume
metadata:
  name: workflow-pv
  namespace: argo-helm
spec:
  capacity:
    storage: 5Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany  # Allows multiple nodes to write
  hostPath:
    path: /Users/rushirajnenuji/K8s/test-helm  # Adjust to the path you want on your host machine
