apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workflow-pvc
  namespace: argo-helm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Match this to your PV's storage
  storageClassName: ""
